name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache pub dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          **/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        cache: true

    - name: Get dependencies
      timeout-minutes: 5
      run: |
        flutter pub get --no-precompile
        flutter pub deps

    - name: Analyze code
      timeout-minutes: 2
      run: flutter analyze --no-fatal-infos

    - name: Run tests
      timeout-minutes: 3
      run: flutter test --no-sound-null-safety

    - name: Build APK
      timeout-minutes: 8
      run: flutter build apk --release --no-tree-shake-icons

    - name: Build App Bundle
      timeout-minutes: 8
      run: flutter build appbundle --release --no-tree-shake-icons

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-keyboard-android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload App Bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-keyboard-android-bundle
        path: build/app/outputs/bundle/release/app-release.aab

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automated release of iOS Keyboard Android App
          
          ## Changes
          - Built from commit: ${{ github.sha }}
          
          ## Installation
          1. Download the APK file
          2. Enable "Unknown sources" in Android settings
          3. Install the APK
          4. Go to Settings > System > Languages & input > Virtual keyboard
          5. Enable "iOS Keyboard"
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}